export const ERROR_STATE = {
  INTERNAL: 'INTERNAL',
  NOT_FOUND: 'NOT FOUND',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  UNAVAILABLE: 'UNAVAILABLE',
  UNKNOWN: 'UNKNOWN',
} as const;

export const ERROR_CODE = {
  INTERNAL: 500,
  NOT_FOUND: 404,
  PERMISSION_DENIED: 403,
  UNAUTHENTICATED: 401,
  UNAVAILABLE: 503,
  UNKNOWN: 520,
} as const;
